version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat linkTestDebugExecutableWindows

test_script:
  - gradlew.bat windowsTest

branches:
  only:
  - master

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.konan

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
