version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/kotlin-mobius
    steps:
      - restore_cache:
          keys:
            - konan
      - checkout
      - run:
          name: Test Jvm mobius-core
          command: ./gradlew jvmTest
      - run:
          name: Test Js mobius-core
          command: ./gradlew jsTest
      - run:
          name: Test Native mobius-core
          command: ./gradlew linuxTest
      - store_artifacts:
          path: "~/kotlin-mobius/jvm/core-jvm/build/reports"
      - save_cache:
          key: konan
          paths:
            - "/home/circleci/.konan"
workflows:
  version: 2
  workflow:
    jobs:
      - build
